# Setup
title:               Alone in a Room
tagline:             'A Blog for Solo RPGs'
description:         'A blog containing solo journaling RPG sessions'
url:                 https://alone-in-a-room.com
baseurl:             ''
permalink:           pretty

host: alone-in-a-room.com

# About/contact
author:
  name:              Chris Rees
  url:               https://alone-in-a-room.com
  email:             i.am@chrisrees.dev

# Build settings
# theme: lanyon
plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tyov:
    output: true
    permalink: /tyov/:path

nav:
  Home:
    - '/'
  Thousand Year Old Vampire:
    - '/tyov/'
    - { Einar: '/tyov/einar' }

autopages:
  enabled: true
  tags:
    enabled: true
  collections:
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

sass:
  style: compressed
  sass_dir: _scss

# Custom vars
version:             1.0.0
