version: '3.4'

services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 9099:4000
    networks:
      - caddy
    labels:
      caddy: alone-in-a-room.com
      caddy.reverse_proxy: "{{upstreams 4000}}"
      caddy.import: "cloudflare-tls"

networks:
  caddy:
    external:
      name: app-config_default
