apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsidXNlcm5hbWUiOiJzZXJuZXVtIiwicGFzc3dvcmQiOiJoWkc3QnNTeE1GUkRvWkt4Ym56VCIsImVtYWlsIjoiaS5hbUBjaHJpc3JlZXMuZGV2IiwiYXV0aCI6ImMyVnlibVYxYlRwb1drYzNRbk5UZUUxR1VrUnZXa3Q0WW01NlZBPT0ifX19
